### ISSUE TITLE
No value for argument 'now' in function call(coolq.py:91)

### ISSUE THREAD

**Issue by MiloWang2048** [cjc7373/zaobot#1]
function remove_timeout_user need 2 args but only 1 passed to it.

**Comment by cjc7373** [comment]
其实有一个更大的bug，在晚上发一个/zaoguys的话，所有在waken_list里的人就都被清空了。。

**Comment by cjc7373** [comment]
fixed at 874688ea3b0e96fc329d3a8931b4d67aa623c8f1
